GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/5


###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Vladimir Putin2",
    "number": "+37360556795"
}

###

GET http://localhost:3001/api/person