GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/5ea872210910420afc1e512e


###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Vladimir Putin3",
    "number": "+12341234"
}

###

GET https://murmuring-beyond-20309.herokuapp.com/api/person