GET http://localhost:3001/api/persons

###

DELETE https://murmuring-beyond-20309.herokuapp.com/api/persons/5


###

POST https://murmuring-beyond-20309.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Vladimir Putin2",
    "number": "+37360556795"
}

###

GET https://murmuring-beyond-20309.herokuapp.com/api/person